import { Client, Team } from "@/types/domain";

export const DEMO_CLIENTS: Client[] = [
  {
    id: "c1",
    name: "M. Dupont - Villa Les Roses",
    location: {
      lat: 48.8566,
      lng: 2.3522,
      address: "12 Rue de la Paix, Paris",
    },
    contract: {
      id: "ctr1",
      clientId: "c1",
      recurrence: "weekly",
      dayOfWeek: 2,
      durationMinutes: 120,
      interventionType: "mowing",
      requiredEquipment: ["lawn_tractor", "blower"],
      weatherConstraints: {
        maxWindSpeed: 30,
        noRainForecast: true,
        minTemperature: 5,
        maxTemperature: 35,
      },
      startDate: new Date("2025-01-01"),
      priority: 3,
    },
  },
  {
    id: "c2",
    name: "Entreprise Verte SA",
    location: {
      lat: 48.8589,
      lng: 2.347,
      address: "45 Av des Champs-Élysées, Paris",
    },
    contract: {
      id: "ctr2",
      clientId: "c2",
      recurrence: "biweekly",
      dayOfWeek: 3,
      durationMinutes: 180,
      interventionType: "hedge_trimming",
      requiredEquipment: ["hedge_trimmer", "utility_vehicle"],
      weatherConstraints: {
        maxWindSpeed: 25,
        noRainForecast: true,
        minTemperature: 5,
        maxTemperature: 35,
      },
      startDate: new Date("2025-01-01"),
      priority: 4,
    },
  },
  {
    id: "c3",
    name: "Parc Municipal",
    location: {
      lat: 48.855,
      lng: 2.36,
      address: "Jardin des Plantes, Paris",
    },
    contract: {
      id: "ctr3",
      clientId: "c3",
      recurrence: "weekly",
      dayOfWeek: 1,
      durationMinutes: 240,
      interventionType: "maintenance",
      requiredEquipment: ["lawn_tractor", "push_mower", "blower"],
      weatherConstraints: {
        maxWindSpeed: 35,
        noRainForecast: false,
        minTemperature: 0,
        maxTemperature: 40,
      },
      startDate: new Date("2025-01-01"),
      priority: 3,
    },
  },
  {
    id: "c4",
    name: "Mme Martin - Résidence",
    location: {
      lat: 48.852,
      lng: 2.345,
      address: "8 Rue de Rivoli, Paris",
    },
    contract: {
      id: "ctr4",
      clientId: "c4",
      recurrence: "monthly",
      dayOfWeek: 4,
      durationMinutes: 90,
      interventionType: "pruning",
      requiredEquipment: ["chainsaw"],
      weatherConstraints: {
        maxWindSpeed: 20,
        noRainForecast: true,
        minTemperature: 5,
        maxTemperature: 35,
      },
      startDate: new Date("2025-01-01"),
      priority: 2,
    },
  },
  {
    id: "c5",
    name: "Café des Jardins",
    location: {
      lat: 48.86,
      lng: 2.34,
      address: "25 Quai des Orfèvres, Paris",
    },
    contract: {
      id: "ctr5",
      clientId: "c5",
      recurrence: "weekly",
      dayOfWeek: 5,
      durationMinutes: 60,
      interventionType: "weeding",
      requiredEquipment: ["push_mower"],
      weatherConstraints: {
        maxWindSpeed: 40,
        noRainForecast: false,
        minTemperature: 0,
        maxTemperature: 40,
      },
      startDate: new Date("2025-01-01"),
      priority: 2,
    },
  },
];

export const DEMO_TEAMS: Team[] = [
  {
    id: "t1",
    name: "Équipe Alpha",
    members: [
      { id: "m1", firstName: "Jean", lastName: "Martin" },
      { id: "m2", firstName: "Paul", lastName: "Dubois" },
    ],
    assignedEquipment: ["lawn_tractor", "push_mower", "blower"],
    defaultStartLocation: { lat: 48.85, lng: 2.35, address: "Dépôt central" },
    skills: ["mowing", "weeding", "maintenance"],
    unavailableDates: [],
    workSchedule: {
      startTime: "07:00",
      endTime: "17:00",
      lunchBreakMinutes: 60,
      workingDays: [1, 2, 3, 4, 5],
    },
    color: "#22c55e",
  },
  {
    id: "t2",
    name: "Équipe Beta",
    members: [{ id: "m3", firstName: "Pierre", lastName: "Bernard" }],
    assignedEquipment: ["hedge_trimmer", "chainsaw", "utility_vehicle"],
    defaultStartLocation: { lat: 48.85, lng: 2.35, address: "Dépôt central" },
    skills: ["hedge_trimming", "pruning", "maintenance"],
    unavailableDates: [],
    workSchedule: {
      startTime: "07:00",
      endTime: "17:00",
      lunchBreakMinutes: 60,
      workingDays: [1, 2, 3, 4, 5],
    },
    color: "#3b82f6",
  },
];
